export const {
  FILE_TYPE_README,
  FILE_TYPE_FULL_DICTIONARY,
  FILE_TYPE_TEMPLATES,
  FILE_TYPE_CONTROLLED_VOCAB_TSV,
  FILE_TYPE_CONTROLLED_VOCAB_JSON,
  FILE_TYPE_LOADING_EXAMPLE,
} = {
  FILE_TYPE_FULL_DICTIONARY: 'Data Dictionary (PDF)',
  FILE_TYPE_README: 'Data Model README (PDF)',
  FILE_TYPE_TEMPLATES: 'All Data Templates (TSV)',
  FILE_TYPE_CONTROLLED_VOCAB_TSV: 'All Vocabularies (TSV)',
  FILE_TYPE_CONTROLLED_VOCAB_JSON: 'All Vocabularies (JSON)',
  FILE_TYPE_LOADING_EXAMPLE: 'Loading File Examples',
};

export const fileTypes = [
  FILE_TYPE_README,
  FILE_TYPE_FULL_DICTIONARY,
  FILE_TYPE_TEMPLATES,
  FILE_TYPE_CONTROLLED_VOCAB_TSV,
  FILE_TYPE_CONTROLLED_VOCAB_JSON,
  FILE_TYPE_LOADING_EXAMPLE,
];
