export const ActionTypes = {
  UPDATE_LOCALFIND_AUTOCOMPLETE_DATA: 'UPDATE_LOCALFIND_AUTOCOMPLETE_DATA',
  UPDATE_LOCALFIND_UPLOAD_DATA: 'UPDATE_LOCALFIND_UPLOAD_DATA',
  UPDATE_LOCALFIND_UPLOAD_METADATA: 'UPDATE_LOCALFIND_UPLOAD_METADATA',
  RESET_LOCALFIND_UPLOAD_DATA: 'RESET_LOCALFIND_UPLOAD_DATA',
};

export default ActionTypes;
