export const cellTypes = {
  CUSTOM_ELEM: 'CUSTOM_ELEM',
  LINK: 'LINK',
  DISPLAY: 'DISPLAY',
  CHECKBOX: 'CHECKBOX',
  DELETE: 'DELETE',
  DEFAULT: 'DEFAULT',
  FORMAT_DATA: 'FORMAT_DATA',
};

export const dataFormatTypes = {
  FORMAT_BYTES: 'FORMAT_BYTES',
}

export const headerTypes = {
  CUSTOM_ELEM: 'CUSTOM_ELEM',
  DELETE: 'DELETE',
  DEFAULT: 'DEFAULT',
};

export const ComponentTypes = {
  PAGINATION: 'PAGINATION',
  MANAGE_VIEW_COLUMNS: 'MANAGE_VIEW_COLUMNS',
  DOWNLOAD_TABLE_BTN: 'DOWNLOAD_TABLE_BTN',
  CUSTOM_ELEM: 'CUSTOM_ELEM',
};
