const styles = () => ({
  expansionPanelRoot: {
    boxShadow: 'none',
    backgroundColor: '#f4f4f4',
    margin: 'auto',
    position: 'initial',
    '&:before': {
      position: 'initial',
    },
  },
  expansionPanelsideBarItem: {
    boxShadow: 'none',
    borderTop: 'thin solid #B1B1B1',
    '&:last-child': {
      borderBottom: '1px solid #B1B1B1',
    },
    margin: 'auto',
    position: 'initial',
    '&:before': {
      position: 'initial',
    },
  },
  backdrop: {
    zIndex: 99999,
    background: 'rgba(0, 0, 0, 0.1)',
  },
  expansionPanelDetailsRoot: {
    paddingBottom: '8px',
    display: 'unset',
  },
  dropDownIconSubSection: {
    marginLeft: '0px',
    fill: '#000000',
  },
  sectionSummaryText: {
    marginLeft: '3px',
    color: '#000000',
    fontFamily: 'Open Sans',
    fontWeight: '300',
    fontSize: '20px',
    lineHeight: '26px',
    letterSpacing: 0,
  },
  sectionSummaryTextCase: {
    marginLeft: '-6px',
    color: '#000000',
    fontFamily: 'Open Sans',
    fontWeight: '300',
    fontSize: '20px',
    lineHeight: '26px',
    letterSpacing: 0,
    display: 'flex',
    flexDirection: 'column',
    zIndex: 1,
    justifyContent: 'space-between',
    width: '100%',
  },
  sectionSummaryTextContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 2,
    fontFamily: 'Lato',
    fontSize: 20,
    fontWeight: 300,
    marginLeft: 10,
    color: 'gray',
  },
  searchContainer: {
    zIndex: 3,
    paddingTop: '15px',
    marginLeft: '8px',
  },
  subSectionSummaryText: {
    marginLeft: '10px',
    color: '#000000',
    fontFamily: 'Open Sans',
    fontWeight: '600',
    fontSize: '14px',
    textTransform: 'uppercase',
    lineHeight: 0,
    letterSpacing: 0,
    flexShrink: 0,
  },
  customExpansionPanelSummaryRoot: {
    flexDirection: 'row-reverse',
    paddingLeft: 4,
  },
  sortGroup: {
    borderTop: '1px solid #B1B1B1',
    textAlign: 'left',
  },
  sortGroupItem: {
    cursor: 'pointer',
    fontFamily: 'Nunito',
    fontSize: '10px',
    marginRight: '42px',
  },
  sortGroupItemCounts: {
    cursor: 'pointer',
    fontFamily: 'Nunito',
    fontSize: '10px',
  },
  sortGroupIcon: {
    cursor: 'pointer',
    marginRight: '12px',
    marginLeft: '16px',
  },
  selected: {},
  selectedCheckboxDisplay: {
    maxHeight: '200px',
    overflow: 'auto',
  },
  showMore: {
    float: 'right',
    paddingRight: '5px',
    cursor: 'pointer',
    fontSize: '10px',
  },
  findCaseButton: {
    marginLeft: '105px',
    backgroundColor: '#10A075',
    boxSizing: 'border-box',
    height: 30,
    width: 40,
    border: '1.25px solid #0D8461',
    cursor: 'pointer',
    borderRadius: 11,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  uploadButton: {
    boxSizing: 'border-box',
    fontWeight: '400',
    height: 32,
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    backgroundColor: '#10A075',
    color: '#fff',
    border: '1px solid #0D8461',
    borderRadius: 10,
    fontFamily: 'Lato',
    fontSize: 11,
    boxShadow: 'none',
    paddingLeft: 16,
    paddingRight: 12,
    '&:hover': {
      backgroundColor: '#10A075',
    },
  },
  findCaseIcon: {
    width: 17,
    height: 17,
  },
  uploadIcon: {
    height: 19,
    width: 19,
  },
  rail: {
    borderRadius: 4,
    height: 6,
    background: '#A6A6A6',
  },
  thumb: {
    height: 16,
    width: 16,
    background: '#10A075',
  },
  track: {
    borderRadius: 4,
    height: 6,
    background: '#10A075',
    '&~&': {
      background: '#10A075',
    },
  },
  sliderRoot: {
    marginTop: '10px',
    marginLeft: '20px',
    marginRight: 'Auto',
    width: '80%',
  },
  upperBound: {
    fontFamily: 'Nunito',
    fontSize: '10px',
    color: '#000000',
    float: 'right',
    marginLeft: 'Auto',
    marginRight: 'Auto',
    marginBottom: '15px',
  },
  lowerBound: {
    fontFamily: 'Nunito',
    fontSize: '10px',
    color: '#000000',
    float: 'left',
    marginLeft: 'Auto',
    marginRight: 'Auto',
    marginBottom: '15px',
  },
  minValue: {
    fontFamily: 'Nunito',
    fontSize: '15px',
    color: '#000000',
    float: 'left',
    marginLeft: 'Auto',
    marginRight: 'Auto',
    marginBottom: '0px',
  },
  maxValue: {
    fontFamily: 'Nunito',
    fontSize: '15px',
    color: '#000000',
    float: 'right',
    marginLeft: 'Auto',
    marginRight: 'Auto',
    marginBottom: '0px',
  },
  listItemGutters: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '2px 5px 2px 8px',
  },
  sliderText: {
    marginTop: '1.5px',
    color: '#10a075',
    lineHeight: '120%',
    fontFamily: 'Nunito',
    fontSize: '14px',
    float: 'right',
  },
  sliderListItem: {
    marginRight: '12px',
  },
  // Test
  listPadding: {
    paddingBottom: '0px',
  },
  listItemGutter: {
    padding: '2px 5px 2px 8px',
    display: 'flex',
    justifyContent: 'space-between',
  },
  clearFiltersBorder: {
    borderTop: '1px solid black',
    borderBottom: '1px solid #B0CFE1',
  },
  closeRoot: {
    marginLeft: '3px',
    height: 18,
  },
  searchResultDetailText: {
    marginTop: '1.5px',
    marginLeft: '12px',
    color: '#0D8662',
    lineHeight: '120%',
    fontFamily: 'Lato',
    fontSize: '11px',
    fontStyle: 'italic',
  },
  iconSpan: {
    marginTop: '5.2px',
  },
  prevIcon: {
    height: '12px',
    margin: '0px 12px 0px 6px',
  },
});

export default styles;
