export default () => ({
  sortGroup: {
    paddingTop: '10px',
    marginBottom: '5px',
    borderTop: '1px solid #B1B1B1',
    textAlign: 'left',
    marginLeft: '-4px',
    display: 'flex',
    alignItems: 'stretch',
    justifyContent: 'flex-start',
    gap: '8px',
  },
  sortGroupIcon: {
    cursor: 'pointer',
    fontFamily: 'Nunito',
    fontSize: '10px',
    marginRight: '12px',
    marginLeft: '24px',
  },
  sortGroupItem: {
    cursor: 'pointer',
    fontFamily: 'Nunito',
    fontSize: '10px',
    // marginRight: '32px',
  },
  sortGroupItemCounts: {
    cursor: 'pointer',
    fontFamily: 'Nunito',
    fontSize: '10px',
    marginRight: '19px',
    marginLeft: 'auto',
    // marginTop: '5px',
    // float: 'right',
  },
  itemsContainer: {
    maxHeight: '400px',
    overflowY: 'auto',
    overflowX: 'hidden',
    borderTop: '2px solid #AEAEAE',
    borderBottom: '2px solid #AEAEAE',
    marginRight: '-1px',
    '&::-webkit-scrollbar': {
      width: '12px',
      backgroundColor: '#E9F0F4',
      borderLeft: '0.5px solid #B1B1B1',
      borderRight: '0.5px solid #B1B1B1',
    },
    '&::-webkit-scrollbar-track': {
      backgroundColor: '#CECECE',
      border: '3px solid transparent',
      borderRadius: '20px',
      backgroundClip: 'content-box',
    },
    '&::-webkit-scrollbar-thumb': {
      backgroundColor: '#477C90',
      border: '3px solid transparent',
      borderRadius: '20px',
      backgroundClip: 'content-box',
    },
  },
  searchContainer: {
    display: 'flex',
    justifyContent: 'center',
    height: '54px',
  },
});
