export default () => ({
  sortGroup: {
    paddingTop: '10px',
    marginBottom: '5px',
    borderTop: '1px solid #B1B1B1',
    textAlign: 'left',
    marginLeft: '-5px',
  },
  highlight: {
    color: '#b2c6d6',
  },
  sortGroupIcon: {
    cursor: 'pointer',
    fontFamily: 'Nunito',
    fontSize: '10px',
    marginRight: '12px',
    marginLeft: 'auto',
  },
  sortGroupItem: {
    cursor: 'pointer',
    fontFamily: 'Nunito',
    fontSize: '10px',
    marginRight: '32px',
  },
  sortGroupItemCounts: {
    cursor: 'pointer',
    fontFamily: 'Nunito',
    fontSize: '10px',
    float: 'right',
    marginRight: '10px',
  },
  checkedContainer: {
    display: 'flex',
    flexWrap: 'wrap',
  },
  itemsContainer: {
    maxHeight: '582px',
    display: 'flex',
    flexWrap: 'wrap',
    overflowY: 'auto',
    overflowX: 'hidden',
    borderTop: '2px solid #AEAEAE',
    borderBottom: '2px solid #AEAEAE',
    marginRight: '-1px',
    '&::-webkit-scrollbar': {
      width: '12px',
      backgroundColor: '#E9F0F4',
      borderLeft: '0.5px solid #B1B1B1',
      borderRight: '0.5px solid #B1B1B1',
    },
    '&::-webkit-scrollbar-track': {
      backgroundColor: '#CECECE',
      border: '3px solid transparent',
      borderRadius: '20px',
      backgroundClip: 'content-box',
    },
    '&::-webkit-scrollbar-thumb': {
      backgroundColor: '#477C90',
      border: '3px solid transparent',
      borderRadius: '20px',
      backgroundClip: 'content-box',
    },
  },
  sortingContainer: {
    display: 'flex',
    height: '36px',
    alignItems: 'center',
  },
  selectionText: {
    fontFamily: 'Nunito',
    fontWeight: '600',
    fontSize: '16px',
    lineHeight: '17px',
    color: '#7D267E',
    marginLeft: '20px',
  },
  totalText: {
    fontFamily: 'Nunito',
    fontWeight: '300',
    fontSize: '16px',
    lineHeight: '17px',
    color: '#7D267E',
  },
});
