name: Test
permissions: 
  contents: read 
  id-token: write 
on:
  workflow_dispatch:
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
        ECR_REPOSITORY: bento-frontend
        IMAGE_TAG: build_test
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get Tags
      run: |
        git fetch --tags --force --quiet
        #tag=$(git tag -l $GITHUB_REF_NAME* | tail -1 | cut -d "-" -f2-)
        tag=$(git tag -l nothing* | tail -1 | cut -d "-" -f2-)
        if  [ ! -z "$tag" ];
        then
          echo "$tag"
          build_num=$(echo "${tag##*.}")
          echo "$build_num"
          build_num=$((build_num+1))
          echo "$build_num"
          new_tag=$GITHUB_REF_NAME.$build_num
          echo "$new_tag"
        else
          echo "tag not found"
          build_num=1
          new_tag=$GITHUB_REF_NAME.$build_num
          echo "$new_tag"
        fi
