name: Test
permissions: 
  contents: read 
  id-token: write 
on:
  workflow_dispatch:
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
        ECR_REPOSITORY: bento-frontend
        IMAGE_TAG: build_test
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get Tags
      run: |
        git fetch --tags --force --quiet
        tags=$(git tag -l $GITHUB_REF_NAME* | tail -1 | cut -d "-" -f2-)
        #tags=$(git tag -l nothing* | tail -1 | cut -d "-" -f2-)
        #echo "$tags"
        if  [ ! -z "$tags" ];
        then
          echo "$tags"
        else
          echo "tag not found"
        fi
